CREATE DATABASE database_CDJR_GAMES;

USE database_CDJR_GAMES;

-- enlaces
CREATE TABLE users (
    id INT(11) NOT NULL,
    nombre VARCHAR (150) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    passw VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
    ADD PRIMARY KEY (id);

ALTER TABLE users
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

    
